Volodkova Anna db-2
AnnaVolodkova/koa-api-starter pull request #1
Opened 2020-07-23 13:18 UTC by AnnaVolodkova

2020-07-29 12:42 UTC, paralectvkomodey requested changes

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/book-add/index.js
> +  const updatedWriter = await writerService.update({ _id: ctx.params.id },
Не используй неатомарные методы в MongoDB, если можно использовать атомарные. Конкретно, в MongoDB есть полезный оператор $push

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/books-update/index.js
> +    (old) => ({
То же самое. Ты можешь просто переписать books не используя callback, а используя query в монге

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/get-sorted-list/index.js
> +  const numberOfAllDocuments = await writerService.count();
Это лишнее. find по дефолту возвращает количество документов по данной query. https://github.com/paralect/node-mongo/blob/master/API.md#example-5

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/get-sorted-list/index.js
> +    data: writersList,
writersList будет объектом, а клиентом ожидается массив

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/update-writer/index.js
> +  const { data } = ctx.request.body;
Нечто странное. Что такое `data` в теле запроса? Почему мы обновляем `firstName` значением из data?
Хотелось бы видеть более очевидное соответствие клиентских ожиданий и запроса в базу

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/get-all/index.js
> +};
Не очень хорошая практика, отдавать все данные из базы

Во-первых - их может быть очень много, что создаст приличную нагрузку на базу данных и приложение
Во-вторых - ты можешь случайно отдать данные, которые клиент НЕ должен видеть(например, системные ключи или ещё что-нибудь)
В-третьих - у тебя уже есть endpoint, который возвращает список всех авторов, не понятно зачем ещё и этот

2020-07-29 12:42 UTC, paralectvkomodey commented on src/resources/writer/book-add/index.js
> +      books: [...old.books, book],
Так как ты позволяешь клиенту выбирать `id` для книг, то получается, что он может поломать твоё приложение просто введя несколько книг, в которых будет одинаковый `id`.

Генерация `id` для документов должна быть на стороне backend - либо средствами базы(Object ID) либо приложения(UID, GUID, ShortID и так далее)

2020-08-06 08:41 UTC, paralectvkomodey requested changes

2020-08-06 08:41 UTC, paralectvkomodey commented on src/resources/writer/books-update/index.js
> +  ctx.body = await writerService.update({ _id }, { $set: { books } });
судя по [документации](https://github.com/paralect/node-mongo/blob/master/API.md#updatequery-updatefn) update принимает вторым параметром функцию, а у тебя я вижу объект

2020-08-06 08:41 UTC, paralectvkomodey commented on src/resources/writer/update-writer/index.js
> +        firstName, lastName, age, books,
Тут следует отделять 2 поведения на update.

1. В сервисах на update ВСЕГДА должны приходить полные объекты, даже если ты хочешь обновить одно поле
2. В сервисах на update приходят только те поля, которые стоит обновлять

Если миксовать эти два подхода, то может случиться непоправимое - и сервис затрет половину документа, потому что мы просто не отправили эти поля в $set. В данном случае, клиент может забыть отправить age и books, вследствии чего сервис занулит эти поля

В своих приложениях лучше сразу определить данное поведение на старте. И мой совет - в слоях общающихся с базой данных - лучше на update ЯВНО указывать поля, которые стоит обновить. Иначе можно обжечься

2020-08-12 09:22 UTC, paralectvkomodey requested changes

2020-08-12 09:22 UTC, paralectvkomodey commented on src/resources/writer/books-update/index.js
> +        firstName, lastName, age, books,
В данном случае в books id генерируется клиентом. Надо всё-таки на сервере

2020-08-12 09:22 UTC, paralectvkomodey commented on src/resources/writer/create-writer/index.js
> +    firstName, lastName, age, books,
аналогично с `update` методом

2020-08-14 17:32 UTC, paralectvkomodey requested changes

2020-08-14 17:32 UTC, paralectvkomodey commented on src/resources/writer/create-writer/index.js
>      firstName, lastName, age, books,
В javascript метод `map` - не мутирующий. Следовательно id у книг всё еще не будет

```
const booksWithId = books.map(item => ({...item, _id: uid()}));
 await writerService.create({
    firstName, lastName, age, booksWithId
```

2020-08-14 17:32 UTC, paralectvkomodey commented on src/resources/writer/books-update/index.js
>    ctx.body = await writerService._collection.update(
аналогично. map не мутирующий метод

2020-08-14 19:44 UTC, AnnaVolodkova commented on src/resources/writer/create-writer/index.js
>      firstName, lastName, age, books,
![image](https://user-images.githubusercontent.com/56339819/90287037-b78e7180-de7f-11ea-909a-856028ccb3cb.png)

2020-08-14 19:45 UTC, AnnaVolodkova commented on src/resources/writer/create-writer/index.js
>      firstName, lastName, age, books,
Почему?

2020-08-14 19:51 UTC, AnnaVolodkova commented on src/resources/writer/create-writer/index.js
>      firstName, lastName, age, books,
Аа, да, все поняла

2020-08-17 13:28 UTC, merged